[package]
name = "mm"
version = "0.1.0"
edition = "2021"

[dependencies]
open = "5.3.0"
slint = "1.7.2"

[build-dependencies]
slint-build = "1.7.0"
pyo3 = { version = "0.22.2", features = ["auto-initialize"] }