import { Button, VerticalBox, HorizontalBox, GridBox, LineEdit } from "std-widgets.slint";
import "../assets/SUSE-VariableFont_wght.ttf";
import "../assets/SUSE-Regular.ttf";
import "../assets/SUSE-Light.ttf";
import { Globals } from "globals.slint";

export component YoutubePage {
    VerticalLayout {
        HorizontalLayout {
            padding-left: 30px;
            padding-right: 30px;
            padding-top: 10px;
            height: 80px;
            width: 100%;
            alignment: space-between;
            Rectangle {
                clip: true;
                TouchArea {
                    HorizontalBox {
                        alignment: center;
                        padding: 0px;
                        Image {
                            colorize: Globals.themeStatus;
                            vertical-alignment: center;
                            source: @image-url("../assets/night-mode.png");
                        }
                        Text {
                            vertical-alignment: center;
                            horizontal-alignment: right;
                            text: "Dark Mode";
                            font-family: "Vazirmatn";
                            font-weight: 900;
                            font-size: 16px;
                            color: Globals.themeStatus;
                        }
                    }
                    clicked => {
                        Globals.switchTheme();
                    }
                }
            }
            Rectangle { }
            TouchArea {
                clicked => {
                    Globals.close();
                }
                Image {
                    image-fit: contain;
                    source: @image-url("../assets/close.png");
                }
            }
        }

        VerticalLayout {
            h := HorizontalLayout {
                padding-left: 30px;
                padding-top: 0px;
                padding-right: 30px;
                height: 90px;
                width: 100%;
                alignment: space-between;
                Rectangle {
                    clip: true;
                    ret := TouchArea {
                        HorizontalBox {
                            alignment: center;
                            padding: 0px;
                            Image {
                                width: 100px;
                                height: 100%;
                                colorize: ret.has-hover ? @radial-gradient(circle, #25d9a2, #0a6f52, #2687ce, #1a71b0) : @radial-gradient(circle, #25d9a2, #1bb085, #2687ce, #2687ce);
                                vertical-alignment: center;
                                source: @image-url("../assets/media_master.png");
                            }
                            Text {
                                vertical-alignment: center;
                                horizontal-alignment: left;
                                text: "MediaMaster";
                                font-family: "SUSE-Regular";
                                font-weight: 900;
                                font-size: 20px;
                                color: ret.has-hover ? @radial-gradient(circle, #25d9a2, #0a6f52, #2687ce, #1a71b0) : @radial-gradient(circle, #25d9a2, #1bb085, #2687ce, #2687ce);
                            }
                        }
                        clicked => {
                            Globals.WHERE_INDEX = 0;
                            Globals.changePage()
                        }
                    }
                }
                Rectangle {
                    Text {
                        text: "Download from Youtube";
                        vertical-alignment: center;
                        font-family: "SUSE";
                        font-weight: 900;
                        font-size: 25px;
                        color: Globals.themeStatus;
                    }
                }
            }
        }

        GridLayout {
            padding: 50px;
            spacing: 25px;
         Row{
            input := LineEdit {
                placeholder-text: "URL:";
                horizontal-alignment: left;
                font-size: 16px;
                height: 35px;
                edited => {

                }
            }
         }   
        }

        // VerticalLayout {
        //     padding: 20px;
        //     spacing: 10px;

        //     // URL input
        //     HorizontalBox {
        //         Text {
        //             text: "URL:";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //         TextInput {
        //             width: 100%;
        //             text: "Globals.youtubeUrl";
        //         }
        //     }

        //     // Video information
        //     HorizontalBox {
        //         Text {
        //             text: "1 video:";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //         Text {
        //             text: "Starlink Mission.mp4";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //     }

        //     // Stream quality
        //     HorizontalBox {
        //         Text {
        //             text: "Stream Quality:";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //         VerticalBox {
        //             // Example of stream options
        //             for stream in ["mp4 - 1080 - 373.5 MB", "mp4 - 720 - 278.4 MB", "mp4 - 480 - 113.9 MB", "mp4 - 360 - 120.2 MB", "mp4 - 240 - 37.8 MB", "mp4 - 144 - 17.6 MB", "webm - 1080 - 140.7 MB"] :
        //                 TouchArea {
        //                     Text {
        //                         text: stream;
        //                         font-size: 16px;
        //                         color: Globals.themeStatus;
        //                     }
        //                     clicked => {
        //                         // Handle stream selection
        //                     }
        //                 }
                    
        //         }
        //     }

        //     // Thumbnail
        //     HorizontalBox {
        //         Text {
        //             text: "Thumbnail:";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //         Image {
        //             source: @image-url("../assets/Screenshot from 2024-09-06 00-39-58.png");
        //             width: 200px;
        //             height: 100px;
        //         }
        //     }

        //     // Video details
        //     HorizontalBox {
        //         Text {
        //             text: "Name:";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //         Text {
        //             text: "Starlink Mission.mp4";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //     }
        //     HorizontalBox {
        //         Text {
        //             text: "Size:";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //         Text {
        //             text: "450.9 MB";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //     }
        //     HorizontalBox {
        //         Text {
        //             text: "Folder:";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //         Text {
        //             text: "/test";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //     }
        //     HorizontalBox {
        //         Text {
        //             text: "video dash - Resumable:";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //         Text {
        //             text: "Yes";
        //             font-size: 16px;
        //             color: Globals.themeStatus;
        //         }
        //     }

        //     // Download button
        //     Button {
        //         text: "Download";
        //         clicked => {
        //             // Handle download action
        //         }
        //     }
        // }
    }
}
