import { Button, VerticalBox, HorizontalBox, GridBox, GroupBox, StandardListView, ListView, Switch, Palette} from "std-widgets.slint";
import { Border } from "@vivi/foundation.slint";
import { TextField, Icons, IconButton, MagicVerticalBox, GroupBox } from "@vivi/magic.slint";
import "../assets/SUSE-VariableFont_wght.ttf";
import "../assets/SUSE-Regular.ttf";
import "../assets/SUSE-Light.ttf";
import { Globals } from "globals.slint";

export component YoutubePage {

    VerticalLayout {
        HorizontalLayout {
            padding-left: 30px;
            padding-right: 30px;
            padding-top: 10px;
            height: 80px;
            width: 100%;
            alignment: space-between;
            Rectangle {
                clip: true;
                TouchArea {
                    HorizontalBox {
                        alignment: center;
                        padding: 0px;
                        Image {
                            colorize: Globals.themeStatus;
                            vertical-alignment: center;
                            source: @image-url("../assets/night-mode.png");
                        }

                        Text {
                            vertical-alignment: center;
                            horizontal-alignment: right;
                            text: "Dark Mode";
                            font-family: "Vazirmatn";
                            font-weight: 900;
                            font-size: 16px;
                            color: Globals.themeStatus;
                        }
                    }

                    clicked => {
                        Globals.switchTheme();
                    }
                }
            }

            TouchArea {
                clicked => {
                    Globals.close();
                }
                Image {
                    image-fit: contain;
                    source: @image-url("../assets/close.png");
                }
            }
        }

        VerticalLayout {
            h := HorizontalLayout {
                padding-left: 30px;
                padding-top: 0px;
                padding-right: 30px;
                height: 90px;
                width: 100%;
                alignment: space-between;
                Rectangle {
                    clip: true;
                    ret := TouchArea {
                        HorizontalBox {
                            alignment: center;
                            padding: 0px;
                            Image {
                                width: 100px;
                                height: 100%;
                                colorize: ret.has-hover ? @radial-gradient(circle, #25d9a2, #0a6f52, #2687ce, #1a71b0) : @radial-gradient(circle, #25d9a2, #1bb085, #2687ce, #2687ce);
                                vertical-alignment: center;
                                source: @image-url("../assets/media_master.png");
                            }

                            Text {
                                vertical-alignment: center;
                                horizontal-alignment: left;
                                text: "MediaMaster";
                                font-family: "SUSE-Regular";
                                font-weight: 900;
                                font-size: 20px;
                                color: ret.has-hover ? @radial-gradient(circle, #25d9a2, #0a6f52, #2687ce, #1a71b0) : @radial-gradient(circle, #25d9a2, #1bb085, #2687ce, #2687ce);
                            }
                        }

                        clicked => {
                            Globals.WHERE_INDEX = 0;
                            Globals.changePage()
                        }
                    }
                }

                Rectangle {
                    Text {
                        text: "Download from Youtube";
                        vertical-alignment: center;
                        font-family: "SUSE";
                        font-weight: 900;
                        font-size: 25px;
                        color: Globals.themeStatus;
                    }
                }
            }
        }

     

            VerticalLayout {
                padding: 0;
                spacing: 10px;
                GridLayout {
                    padding-left: 50px;
                    padding-right: 50px;
                    padding-top: 25px;
                    spacing: 10px;
                    Row{
                       
                        Switch {
                            horizontal-stretch: 0;
                            text: @tr("Dark mode for palettes");
                            checked: Palette.color-scheme == ColorScheme.dark;
                            toggled => {                
                                Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
                            }
                        }
                    }

                    HorizontalLayout {
                        padding-top: 10px;
                        input := TextField {
                            prefix_icon: Icons.search;
                            IconButton {
                                icon: Icons.clear;
                                inline: true;
                                enabled: input.text != "" && input.enabled;
                                clicked => {
                                    input.text = "";
                                }
                            }

                            placeholder-text: "URL:";
                            horizontal-alignment: left;
                            height: 45px;
                        }



                        download_text := TouchArea {
                            clicked => {
                                // Globals.startInstaller();
                            }
                            Rectangle {
                                width: 120px;
                                height: 44px;
                                background: Globals.currentTheme ? white : Globals.primaryDark;
                                animate background, drop-shadow-color, drop-shadow-blur {
                                    duration: 275ms;
                                    easing: ease-in-out;
                                }
                                border-radius: 8px;
                                drop-shadow-color: Globals.currentTheme ? #d9d9d9 : #404040;
                                drop-shadow-blur: 12px;
                                drop-shadow-offset-x: 2px;
                                drop-shadow-offset-y: 2px;
                                HorizontalBox {
                                    alignment: center;
        
                                    Image {
                                        colorize: Globals.currentTheme ? transparent : white; //#0D40BF;
                                        image-fit: fill;
                                        source: @image-url("../assets/inbox.png");
                                    }
        
                                    Text {
                                        vertical-alignment: center;
                                        text: "Download";
                                        font-family: "Vazirmatn";
                                        color: download_text.has-hover ? @radial-gradient(circle, #25d9a2, #0a6f52, #2687ce, #1a71b0) : @radial-gradient(circle, #25d9a2, #1bb085, #2687ce, #2687ce);
                                        font-size: 16px;
                                        font-weight: 900;
                                    }
                                }
                            }
                        }


                    }
                }

                GridLayout {
                    padding-right: 50px;
                    padding-left: 50px;
                    padding-bottom: 10px;
                    spacing: 10px;
                    Rectangle {
                        
                        colspan: 2;
                        HorizontalBox {
                            vertical-stretch: 1;
                            GroupBox {
                                
                                ListView {
                                    
                                    vertical-stretch: 0;
                                    for i in [0, 1, 2, 3, 4, 5, 6] : HorizontalBox{
                                        Text {
                                            text: @tr("item {} ", i);
                                            
                                        }
                                    }
                                }
                            }
                        }
                    }

                    Rectangle {
                        col: 2;
                        colspan: 2;
                        HorizontalBox {
                            
                            vertical-stretch: 1;
                            GroupBox {
                                
                                ListView {
                                    vertical-stretch: 0;
                                    for stream in ["mp4 - 1080 - 373.5 MB", "mp4 - 720 - 278.4 MB", "mp4 - 480 - 113.9 MB", "mp4 - 360 - 120.2 MB", "mp4 - 240 - 37.8 MB", "mp4 - 144 - 17.6 MB", "webm - 1080 - 140.7 MB"] : HorizontalBox{
                                        Text {
                                            // text: stream;
                                         
                                        }
                                    }
                                }
                            }
                        }
                    }

                    Rectangle {
                        background: black;
                        col: 3;
                        row: 1;
                        rowspan: 3;
                    }

                    Rectangle {
                        background: blue;
                        row:1;
                        rowspan: 3;
                        colspan: 3;
                    }
                }
            }
    }
}
