    import { VerticalBox } from "std-widgets.slint";

    export global CalcLogic {
        callback button_pressed(string);
    }

    component Button {
        in property <string> text;
        min-height: 30px;
        min-width: 30px;
        in property <brush> background: teal;
        Rectangle {
            background: ta.pressed ? #747e88 : ta.has-hover ? background.brighter(10%) : background;
            animate background { duration: 150ms; }
            border-radius: 4px;
            border-width: 2px;
            border-color: self.background.darker(20%);
            ta := TouchArea {
                clicked => {
                    CalcLogic.button_pressed(root.text);
                }
            }
        }
        Text { text: root.text; color: whitesmoke;}
    }
    
    export component App inherits Window {

        in property <int> value: 0;
    
        GridLayout {
            padding: 10px;
            spacing: 10px;
            Text {
                text: value; 
                colspan: 3;
            }
            Row{
                Button { text: "1"; }
                Button { text: "2"; }
                Button { text: "3"; }
                Button { text: "+"; background: gray; }
            }
            Row{
                Button { text: "4"; }
                Button { text: "5"; }
                Button { text: "6"; }
                Button { text: "-"; background: gray; }
            }
            Row{
                Button { text: "7"; }
                Button { text: "8"; }
                Button { text: "9"; }
                Button { text: "*"; background: gray; }
            }
            Row{
                Button { text: "0"; }
                Button {
                    text: "=";
                    col: 2;
                    background: @linear-gradient(-20deg, #b38fae, #a365e3);
                }
                Button { text: "/"; background: gray; }
            }
        }
    }

