import { Button, VerticalBox, HorizontalBox, GridBox} from "std-widgets.slint";
import "assets/vazirmatn.ttf";
import "assets/Inter-Regular.ttf";
import {EnglishApp, YoutubePage} from "layout/pages.slint";
import { Globals } from "layout/globals.slint";
// import { FilledButton, MagicVerticalBox, MagicText } from "@vivi/magic.slint";

// ReExport for Native access
export { Globals }

export component App inherits Window {
    width: 949px;
    height: 650px;
    no-frame: false;
    background: transparent;
    Rectangle {
        border-radius: 15px;
        background: Globals.currentTheme ? Globals.lightTheme : Globals.darkTheme;
        animate background {
            duration: 275ms;
            easing: ease-in-out;
        }
        VerticalLayout {
            if Globals.WHERE_INDEX == 0: EnglishApp { }
            if Globals.WHERE_INDEX == 1: YoutubePage { }
        }
    }

   
}
